import numpy as np
from ase.io import write
from pynep.io import load_nep, dump_nep
from tools import get_gamma

print("启动双端截断 Gamma 筛选器...")

nep_file = "nep.txt"
input_xyz = "NEP-dataset-good.xyz"
active_set_file = "active_set.asi"

traj = load_nep(input_xyz)

print(f"输入文件: {input_xyz}")
print(f"输入结构数: {len(traj)}")

print("正在调用 pynep 计算所有帧的 Gamma 外推等级...")
get_gamma(traj, nep_file, active_set_file)

GAMMA_MIN = 3.0
GAMMA_MAX = 70.0

out_traj = []
count_low = 0
count_high = 0
count_good = 0

gamma_report_file = "gamma_report.dat"

with open(gamma_report_file, "w") as f:
    f.write("# Gamma report generated by new_select_gamma.py\n")
    f.write(f"# input_xyz = {input_xyz}\n")
    f.write(f"# nep_file = {nep_file}\n")
    f.write(f"# active_set_file = {active_set_file}\n")
    f.write(f"# GAMMA_MIN = {GAMMA_MIN}\n")
    f.write(f"# GAMMA_MAX = {GAMMA_MAX}\n")
    f.write("#\n")
    f.write("# frame_id  natoms  gamma_min  gamma_mean  gamma_max  max_gamma_atom_index  status\n")

    for frame_id, atoms in enumerate(traj):
        if "gamma" not in atoms.arrays:
            raise RuntimeError(
                f"第 {frame_id} 帧没有 gamma 信息，请检查 get_gamma 是否正常运行。"
            )

        gamma = atoms.arrays["gamma"]

        gamma_min = np.min(gamma)
        gamma_mean = np.mean(gamma)
        gamma_max = np.max(gamma)
        max_gamma_atom_index = int(np.argmax(gamma))

        if gamma_max < GAMMA_MIN:
            status = "LOW"
            count_low += 1
        elif gamma_max > GAMMA_MAX:
            status = "HIGH"
            count_high += 1
        else:
            status = "SELECTED"
            count_good += 1
            out_traj.append(atoms)

        f.write(
            f"{frame_id:8d} "
            f"{len(atoms):8d} "
            f"{gamma_min:16.8f} "
            f"{gamma_mean:16.8f} "
            f"{gamma_max:16.8f} "
            f"{max_gamma_atom_index:8d} "
            f"{status}\n"
        )

print(f"📄 每个结构的 Gamma 信息已输出到: {gamma_report_file}")

print(f"   总输入帧数: {len(traj)}")
print(f"   下限无效结构 (Gamma < {GAMMA_MIN}): {count_low} 帧")
print(f"   上限无效结构 (Gamma > {GAMMA_MAX}): {count_high} 帧")
print(f"   有效区间: {len(out_traj)} 帧")
print("-" * 50)

# 输出筛选后的结构
if len(out_traj) > 0:
    try:
        dump_nep("large_gamma.xyz", out_traj)
    except Exception as e:
        print(f"dump_nep 输出失败，改用 ase.io.write。原因: {e}")
        write("large_gamma.xyz", out_traj)

    print(f"已将 {len(out_traj)} 个结构保存至 large_gamma.xyz")
else:
    print("警告：当前截断范围内没有挑出任何结构！")
    print("你可以查看 gamma_report.dat 里面的 gamma_max 分布，然后重新设置 GAMMA_MIN / GAMMA_MAX。")
